add breadcrumbs component
govtechmy/myds pull request #16
Opened 2024-10-10 12:43 UTC by amalasyrafs

- added breadcrumbs component
- added stories for breadcrumbs

TODO:
- [ ]  write dev docs for breadcrumbs in fumadocs (will proceed once component is approved)

2024-10-10 14:54 UTC, irfancoder requested changes
Good and very clean work! Good to merge after feedbacks are addressed

2024-10-10 14:54 UTC, irfancoder commented on packages/react/src/components/breadcrumbs.tsx
1. Rename variant option: ~~alternative~~ to `fill`
2. Rename component: Breadcrumbs* to Breadcrumb* -- eg. `BreadcrumbsItem` => `BreadcrumbItem` and so on.

2024-10-10 14:54 UTC, irfancoder commented on packages/react/src/components/breadcrumbs.tsx
> +    {children ?? <ChevronRight />}
Use `||` instead. Wider scope for checking falsy value when rendering component

https://medium.com/nerd-for-tech/the-difference-between-and-operators-in-javascript-nodejs-3696b0ce02ff

2024-10-11 03:11 UTC, amalasyrafs commented
feedback addressed in the new commit

2024-10-11 08:00 UTC, irfancoder approved these changes

2024-10-11 08:04 UTC, merged