Feat/tag
govtechmy/myds pull request #34
Opened 2024-10-17 07:37 UTC by ahmadanwar93

- Tag component 
- Tag stories
- Extend Tailwind merge as per this issue (https://github.com/dcastil/tailwind-merge/issues/297)

2024-10-17 11:08 UTC, irfancoder requested changes

2024-10-17 11:08 UTC, irfancoder commented on packages/react/src/components/tag.tsx
1. Missing border
2. Check if the dot grows according to size

2024-10-17 11:08 UTC, irfancoder commented on packages/react/src/components/tag.tsx
> +      },
Rename:
1. ~~tagStyle~~ mode
2. ~~style1~~ pill
3. ~~style2~~ default

2024-10-18 01:15 UTC, ahmadanwar93 commented on packages/react/src/components/tag.tsx
> +        warning: "bg-bg-warning-50 text-txt-warning",
Done

2024-10-18 01:18 UTC, ahmadanwar93 commented on packages/react/src/components/tag.tsx
> +  showStatusDot?: boolean;
Done as well

2024-10-18 01:19 UTC, ahmadanwar93 commented on packages/react/src/components/tag.tsx
> +      },
Done as well

2024-10-18 02:06 UTC, ahmadanwar93 commented on packages/react/src/components/tag.tsx
Done as well

2024-10-18 02:16 UTC, irfancoder approved these changes
Looking good

2024-10-18 02:31 UTC, merged