Feat/pagination
govtechmy/myds pull request #39
Opened 2024-10-21 06:54 UTC by amalasyrafs

2024-10-21 07:56 UTC, irfancoder requested changes

2024-10-21 07:56 UTC, irfancoder commented on packages/react/src/components/pagination.tsx
1. Lacking support for customisation of pagination items. Eg. how to handle i18n in `Previous` & `Next`, use different icon etc
2. Can you give an example how to integrate this with server pagination? ie. where the state is taken from query params
3. Rename:
- ~~basic~~ `simple`
- ~~number~~ `default`
- ~~basic-alternate~~ `full`

2024-10-21 11:45 UTC, amalasyrafs commented
hi @irfancoder ,

rename the types for pagination and added server example. but i have to add new page `pagination-server.stories.tsx` to be able to exhibit this example. 

or if you know any other method to do this, please lmk.

2024-10-22 03:01 UTC, irfancoder requested changes

2024-10-22 03:01 UTC, irfancoder commented on apps/storybook/stories/pagination-server.stories.tsx
Dont need a separate component entry here. Just need 1 sample use-case story inside `pagination.stories.tsx`

2024-10-22 04:29 UTC, amalasyrafs commented on packages/react/src/components/button.tsx
> +export interface ButtonProps
exporting this ButtonProps so that could reuse the type across the library

2024-10-24 03:38 UTC, merged

2024-10-24 03:40 UTC, irfancoder commented
@amalasyrafs check the reviewed `asChild` implementation & the expected usage in the story. Something to keep it in mind when building future components. Keep up the good work!