chore : navbar
govtechmy/myds pull request #94
Opened 2024-12-03 05:20 UTC by harrisazmi

Component Navbar

2025-01-18 02:51 UTC, irfancoder requested changes

2025-01-18 02:51 UTC, irfancoder commented on packages/react/src/components/navbar.tsx
> +}) => {
https://myds-storybook-git-feat-componentnavbar-gnu-malaysia.vercel.app/?path=/story/govtechmy-myds-react-navbar--navbar-custom-myds

Tablet & mobile view, menu dia tak fill width (?)

2025-01-18 02:51 UTC, irfancoder commented on apps/storybook/stories/navbar.stories.tsx
> +                <NavItemsDropdown menu="Menu Dropdown">
Example not updated. Still using `...Desktop`, `...Mobile` components

2025-01-21 05:57 UTC, harrisazmi commented on apps/storybook/stories/navbar.stories.tsx
> +                <NavItemsDropdown menu="Menu Dropdown">
Updated

2025-01-23 05:14 UTC, irfancoder approved these changes

2025-01-23 05:14 UTC, merged